// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: grpc/interface.proto

package go_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReplicaServiceClient is the client API for ReplicaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReplicaServiceClient interface {
	SendSomeMessage(ctx context.Context, in *SomeMessage, opts ...grpc.CallOption) (*SomeMessage, error)
	Increment(ctx context.Context, in *RequestIncrement, opts ...grpc.CallOption) (*ResponseIncrement, error)
}

type replicaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicaServiceClient(cc grpc.ClientConnInterface) ReplicaServiceClient {
	return &replicaServiceClient{cc}
}

func (c *replicaServiceClient) SendSomeMessage(ctx context.Context, in *SomeMessage, opts ...grpc.CallOption) (*SomeMessage, error) {
	out := new(SomeMessage)
	err := c.cc.Invoke(ctx, "/protos.ReplicaService/sendSomeMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaServiceClient) Increment(ctx context.Context, in *RequestIncrement, opts ...grpc.CallOption) (*ResponseIncrement, error) {
	out := new(ResponseIncrement)
	err := c.cc.Invoke(ctx, "/protos.ReplicaService/Increment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicaServiceServer is the server API for ReplicaService service.
// All implementations must embed UnimplementedReplicaServiceServer
// for forward compatibility
type ReplicaServiceServer interface {
	SendSomeMessage(context.Context, *SomeMessage) (*SomeMessage, error)
	Increment(context.Context, *RequestIncrement) (*ResponseIncrement, error)
	mustEmbedUnimplementedReplicaServiceServer()
}

// UnimplementedReplicaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedReplicaServiceServer struct {
}

func (UnimplementedReplicaServiceServer) SendSomeMessage(context.Context, *SomeMessage) (*SomeMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSomeMessage not implemented")
}
func (UnimplementedReplicaServiceServer) Increment(context.Context, *RequestIncrement) (*ResponseIncrement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Increment not implemented")
}
func (UnimplementedReplicaServiceServer) mustEmbedUnimplementedReplicaServiceServer() {}

// UnsafeReplicaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplicaServiceServer will
// result in compilation errors.
type UnsafeReplicaServiceServer interface {
	mustEmbedUnimplementedReplicaServiceServer()
}

func RegisterReplicaServiceServer(s grpc.ServiceRegistrar, srv ReplicaServiceServer) {
	s.RegisterService(&ReplicaService_ServiceDesc, srv)
}

func _ReplicaService_SendSomeMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SomeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).SendSomeMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ReplicaService/sendSomeMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).SendSomeMessage(ctx, req.(*SomeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaService_Increment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestIncrement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).Increment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ReplicaService/Increment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).Increment(ctx, req.(*RequestIncrement))
	}
	return interceptor(ctx, in, info, handler)
}

// ReplicaService_ServiceDesc is the grpc.ServiceDesc for ReplicaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReplicaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.ReplicaService",
	HandlerType: (*ReplicaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sendSomeMessage",
			Handler:    _ReplicaService_SendSomeMessage_Handler,
		},
		{
			MethodName: "Increment",
			Handler:    _ReplicaService_Increment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/interface.proto",
}
